### PR TITLE
superficial-changes

### PR DESCRIPTION
**Pull request by amberisvibin**
- add 404
- add book description and language (accessibility)
- move declaration
- fix benchmark link (no longer worked)
- fine tune search
- add some newlines to get rid of git diff warnings

### CODE REVIEW

**Comment by fennecdjay** [comment]
Is it just me, or do we have a bizzare behavior on 404?
Going to a non existing page, say, [this one](https://fennecdjay.github.io/Gwion/g), shows an unstyled page. At first I thought it was my browser (I recently switched to dissenter), but I also tested with firefox and it looks the same.
When inspecting the page, console shows it can't find the css and javascript.
I don't know whether it's on our side or something in mdbook, however [this page](https://rust-lang.github.io/mdBook/format/qsdfqsfd) looks ok.
How does it work for you?
And, if it is broken, do you have any ideas?

**Comment by fennecdjay** [comment]
Just found it was broken (for me only?) on other sites:like [here](https://rust-lang.github.io/async-book/index.htmlqsdqs)

**Comment by amberisvibin** [comment]
Hmm. No, it's broken for me as well. Both our book and the async book. The page that shows up is also not the one I made. This is odd. I'll check the mdbook repo for issues.

**Comment by amberisvibin** [comment]
Ah, I forgot to add the 404-page to the `book.toml`. That would do it. I'll add it to the PR.

**Comment by fennecdjay** [comment]
Wouldn't it make sense to put it in the docs folder?
Also Mdbook's documentation state that 404.md is the default.

**Comment by amberisvibin** [comment]
You are right. I'm having some git issues at the moment, but when I fix it I'll move it.

**Comment by fennecdjay** [comment]
Git is tricky sometimes. I spend a fair amount of time yesterday to get the benchmark CI working, mostly (if not only) because of git :unamused:

**Comment by amberisvibin** [comment]
Okay, I've got it fixed. It's all in PR #7.

**Pull request merged**
