### PR TITLE
Update `Configure.mdr` to new build system, etc.

### PR DESCRIPTION
**Pull request by amberisvibin**
- Update `Configure.mdr` to new build system
- Add info to install page
- Update some READMEs for sections with flavor text

### CODE REVIEW

**Review by fennecdjay — COMMENTED** [review]
Jolly good! :smile:

**Comment by fennecdjay** [comment]
There's a squash command :champagne:
I'm gonna try it now!
Thanks again.

**Comment by amberisvibin** [comment]
That squash command seems to have made the merge a commit for both me and you?
But it got rid of the other merges, so thats good!

**Comment by amberisvibin** [comment]
It also makes my fork think it's still ahead of this branch... hmm...
Git mastery eludes me

**Comment by amberisvibin** [comment]
I figured out how to stop the extra commits on my end, with `git pull --rebase`, so the squash commits are no longer necessary I think.

**Comment by fennecdjay** [comment]
`git rebase` is still a mystery to me, no matter how much I read about it.
That squash feature was pretty good IMHO.

**Pull request merged**
