### PR TITLE
:book: Add detailed contributing guide

### PR DESCRIPTION
**Pull request by TotallyNotChase**

### CODE REVIEW

**Comment by fennecdjay** [comment]
Looks good to me :smile:
I just wonder wether dependencies should include a c compiler (currently the project is tested against `gcc` and `clang`). What do you think?
Otherwise seems ready for merge, thank you!

**Comment by TotallyNotChase** [comment]
@fennecdjay  Is there a specific minimum version of gcc and clang that gwion needs? could add that

**Comment by fennecdjay** [comment]
Honestly I don't know :confused:
It was working right on travis-ci a while back. It probably just needs a compiler that knows the c99 specification.
Maybe `a recent version` would be enough.

**Comment by fennecdjay** [comment]
LGTM :champagne:
Just waiting for your confirmation to merge!
Thank you for the fast reaction.

**Comment by TotallyNotChase** [comment]
@fennecdjay sounds good

**Comment by fennecdjay** [comment]
Makes my day!

**Comment by fennecdjay** [comment]
@allcontributors-bot please add @TotallyNotChase for documentation.

**Pull request merged**
